### ISSUE TITLE
OutOfMemoryError in koog 0.5.0

### ISSUE THREAD

**Issue by islamiusupov** [JetBrains/koog#947]
I upgraded from koog 0.4.1 to the latest 0.5.0 and now I'm getting a compilation error. As I said earlier, everything compiles on version 0.4.1. There should be enough memory, as I allocate 16gb in idea
:
<pre>``
java.lang.OutOfMemoryError: Java heap space
	at org.jetbrains.kotlin.utils.SmartList.add(SmartList.java:96)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:338)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.doAddOtherSystem(NewConstraintSystemImpl.kt:399)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.addOtherSystem(NewConstraintSystemImpl.kt:359)
	at org.jetbrains.kotlin.fir.resolve.inference.FirDelegatedPropertyInferenceSession.processPartiallyResolvedCall(FirDelegatedPropertyInferenceSession.kt:93)
	at org.jetbrains.kotlin.fir.resolve.inference.FirCallCompleter.completeCall(FirCallCompleter.kt:139)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformFunctionCallInternal$resolve(FirExpressionsResolveTransformer.kt:529)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformFunctionCall(FirExpressionsResolveTransformer.kt:453)

``<pre>

**Comment by aozherelyeva** [comment]
Hi @islamiusupov , thanks for the report! Could you please check if the issue remains in the 0.5.1 version?
